### ISSUE TITLE
minimalistisch 

### ISSUE THREAD

**Issue by kosterm14** [WesleySchorel/connect-your-tribe-squad-page#2]
ik vind je website mooi minimalistisch gemaakt, je komt meteen op je website en ziet de belangrijke info en er zijn geen onnodige dingen

![image](https://user-images.githubusercontent.com/61830362/219615228-48ed9ff8-0128-4432-82e1-5e6dbef8bc58.png)

Ik zou wel het stuk met de squadnaam kleiner maken om de focus meer te leggen op de members

**Comment by WesleySchorel** [comment]
Bedankt! Ik heb de squadnaam een stukje kleiner gemaakt.
