### ISSUE TITLE
onnodig

### ISSUE THREAD

**Issue by kosterm14** [WesleySchorel/connect-your-tribe-squad-page#3]
Ik zou de fdnd image weglaten. Het voelt nu een beetje onnodig aangezien je er de squadnaam onder hebt en omdat dit een squadpage van fdnd is weet je dat.

![image](https://user-images.githubusercontent.com/61830362/219615981-5aebdb07-df23-41ef-966c-7ccb567b539c.png)

**Comment by WesleySchorel** [comment]
Ik heb de afbeelding weggehaald

**Comment by kosterm14** [comment]
Wow Wesley ik zag net dat je dit hebt opgelost. Je bent erg serieus met mijn feedback omgegaan
