### ISSUE TITLE
Sub informatie grootte en hierarchie

### ISSUE THREAD

**Issue by Tolga1999** [WesleySchorel/connect-your-tribe-squad-page#8]
Maak de github namen niet allemaal hoofdletters, geef het een kleinere naam voor hiërarchie
![image](https://user-images.githubusercontent.com/112855878/219619933-ea4103a7-b937-4076-96af-83475be5a755.png)

**Comment by WesleySchorel** [comment]
Ik heb "text-transform: uppercase;" weggehaald. De githubHandle is nu kleiner dan de naam.
