### ISSUE TITLE
H1 top padding

### ISSUE THREAD

**Issue by Tolga1999** [WesleySchorel/connect-your-tribe-squad-page#9]
maak de witruimte boven de h1 consistent met de witruimte onder de H1, de teskst zelf heeft nog een padding waardoor het meer ruimte heeft dan de onderkant
![image](https://user-images.githubusercontent.com/112855878/219620613-ebc093bc-c4aa-4548-8c94-d6277cf72348.png)

**Comment by WesleySchorel** [comment]
Ik heb de witruimtes even groot gemaakt.
